spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/springboot-project?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : wjdrksp1012

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: ture
      ddl-auto: create
  mvc:
    hiddenmethod:
      filter:
        enable:true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE